// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ApiProductos.Entities
{
    public partial class Customer
    {
        public int CustumerId { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
    }
}